services:
  # Meilisearch - Search engine
  meilisearch:
    image: getmeili/meilisearch:v1.24.0
    container_name: kidsearch-meilisearch
    restart: unless-stopped
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: ${MEILI_KEY:-masterKey}
      MEILI_NO_ANALYTICS: true
      # Optimized for 6GB RAM
      MEILI_MAX_INDEXING_MEMORY: 512MB
      MEILI_MAX_INDEXING_THREADS: 2
    volumes:
      # Use Docker volume instead of hardcoded Synology path
      - ./meili_data:/meili_data
    networks:
      - kidsearch-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Text Embeddings Inference - Optimized for DS220+ (6GB RAM, 2 cores)
  embeddings_small:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.8.2
    container_name: embeddings_small
    restart: unless-stopped
    networks:
      - kidsearch-network
    environment:
      HF_HUB_DISABLE_TELEMETRY: "1"
      # Limit CPU threads (DS220+ has 2 cores)
      RAYON_NUM_THREADS: "2"
      OMP_NUM_THREADS: "2"
    ports:
      - "8090:80"  # Expose Prometheus metrics
    command:
      - "--model-id"
      - "intfloat/multilingual-e5-small"
      - "--port"
      - "80"
      # 🔧 Balanced settings for stability
      - "--max-concurrent-requests"
      - "4"
      - "--max-client-batch-size"
      - "6"
      - "--max-batch-tokens"
      - "10240"
      - "--pooling"
      - "mean"
      - "--max-batch-requests"
      - "6"
    volumes:
      - ./models_cache:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  # KidSearch Dashboard & API (All-in-one)
  kidsearch-all:
    image: gandulf78/kidsearch:latest
    container_name: kidsearch-all
    restart: unless-stopped
    ports:
      - "8501:8501"  # Dashboard
      - "8082:8080"  # API
    dns:
      - 1.1.1.3
      - 1.0.0.3
    environment:
      SERVICE: all
      LOG_LEVEL: ${LOG_LEVEL:-info}  # Use info by default, not debug
      API_ENABLED: "true"
      API_WORKERS: ${API_WORKERS:-2}

      # Display URLs
      DISPLAY_HOST: ${DISPLAY_HOST:-}
      DASHBOARD_DISPLAY_HOST: ${DASHBOARD_DISPLAY_HOST:-}
      API_DISPLAY_HOST: ${API_DISPLAY_HOST:-}

      # Meilisearch connection
      MEILI_URL: http://meilisearch:7700
      MEILI_KEY: ${MEILI_KEY:-masterKey}
      INDEX_NAME: ${INDEX_NAME:-kidsearch}

      # --- Embedding Configuration ---
      EMBEDDING_PROVIDER: ${EMBEDDING_PROVIDER:-huggingface}
      HUGGINGFACE_MODEL: ${HUGGINGFACE_MODEL:-intfloat/multilingual-e5-small}
      HUGGINGFACE_API_URL: ${HUGGINGFACE_API_URL:-http://embeddings_small:80/embed}
      HUGGINGFACE_EMBEDDING_BATCH_SIZE: ${HUGGINGFACE_EMBEDDING_BATCH_SIZE:-6}
      GEMINI_API_KEY: ${GEMINI_API_KEY:-}
      GEMINI_EMBEDDING_BATCH_SIZE: ${GEMINI_EMBEDDING_BATCH_SIZE:-20}
      EMBEDDING_BATCH_DELAY: ${EMBEDDING_BATCH_DELAY:-2}

      # --- Reranking Configuration (Optimized for DS220+ 6GB RAM) ---
      RERANKING_ENABLED: ${RERANKING_ENABLED:-true}
      RERANKER_API_URL: ${RERANKER_API_URL:-http://embeddings_small:80/embed}
      RERANKER_MODEL: ${RERANKER_MODEL:-intfloat/multilingual-e5-small}
      RERANKER_BATCH_SIZE: ${RERANKER_BATCH_SIZE:-3}
      RERANKER_MAX_CHARS: ${RERANKER_MAX_CHARS:-200}
      RERANKER_CACHE_SIZE: ${RERANKER_CACHE_SIZE:-4096}
      RERANKER_TIMEOUT: ${RERANKER_TIMEOUT:-12}

      # Weights for result merging
      MEILISEARCH_WEIGHT: ${MEILISEARCH_WEIGHT:-0.7}
      CSE_WEIGHT: ${CSE_WEIGHT:-0.3}

      # --- Google APIs ---
      GOOGLE_CSE_API_KEY: ${GOOGLE_CSE_API_KEY:-}
      GOOGLE_CSE_ID: ${GOOGLE_CSE_ID:-}

      # --- Wiki API (Vikidia) ---
      WIKI_API_URL: ${WIKI_API_URL:-https://fr.vikidia.org/w/api.php}
      WIKI_SITE_URL: ${WIKI_SITE_URL:-https://fr.vikidia.org/wiki/}
      WIKI_SITE_NAME: ${WIKI_SITE_NAME:-Vikidia}

    volumes:
      - /volume1/Laurent/docker/kidsearch/data:/app/data
      - /volume1/Laurent/docker/kidsearch/config:/app/config
      - /volume1/Laurent/docker/kidsearch/streamlit:/app/.streamlit
    networks:
      - kidsearch-network
    depends_on:
      meilisearch:
        condition: service_healthy
      embeddings_small:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  kidsearch-network:
    driver: bridge